<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Collectus : Service professionel de collecte et recyclage de matériel bureautique</title>
	<meta charset="UTF-8">
	<meta name="description" content="Collectus" /> 
	<meta name="keywords" content="" />
	<meta name="Indentifier-URL" content="http://www.collectus.fr/" />
	<link href="style.css" rel="stylesheet" type="text/css" />
	<link rel="icon" type="image/png" href="../images/favicon.ico" >

	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45629393-1', 'collectus.fr');
  ga('send', 'pageview');

</script>

	
	</head>
<body onLoad="check_infos();currentPage('homepage');">
<div id="headpage"><span>Copyright © Collect'us</span></div>
<div id="conteneur">
	<?php include('head.php'); ?>
	<?php include('shmenu.php'); ?>
	<div id="contenu">
	
		<?php include('formulaire.php'); ?>
		<div id="center">
			<div id="text">
			<span style="font-weight:bold;">WHO IS COLLECT’US ?</span>
			<br><br>Based in Paris, Collect'us is a company that not only provides a collection service dedicated for professionals but also redirects the waste back into the remanufacturing stream for re-use.
			We recover, collect and sort any type of trash generated by office activities: 
			<br><br>
			&nbsp;&nbsp;&nbsp;&nbsp;OEM Virgin empty Ink jet cartridges and toners
			<br>&nbsp;&nbsp;&nbsp;&nbsp;Mobile phones
			<br>&nbsp;&nbsp;&nbsp;&nbsp;Computers
			<br>&nbsp;&nbsp;&nbsp;&nbsp;Batteries 
			<br>&nbsp;&nbsp;&nbsp;&nbsp;Printed circuit board 

			<br><br>Our expertise and experience enable us to offer an optimized quality service. We collect for Groups, SMEs, local administrations, academic institutions and associations providing them dedicated solutions according to their size, structure and logistical requirements. Also, Collect'us is involved in community life developing a partnership to support the french Telethon.

			<br><br><br><span style="font-weight:bold;">SELLING OUR PRODUCTS</span>
			<br><br>From our collection, we have a large stock and many references of used products to sell. Thanks to our platform, our storage capacity allows us to offer customers significant amounts of several models. We offer high quality products ensuring you a safe delivery of merchandise that meets your expectations.  Everything we sell is pre-tested and sorted through rigorous testing process.
			We provide on request, according to our conditions: OEM Virgin empty or unused cartridges, mobile phones, computer equipment, CD-ROM and printed circuit board.
			You can have more details on our terms of sale and available stocks.
			Contact us on our email address collectus@collectus.fr
			
			<br><br><br><span style="font-weight:bold;">PURCHASE OF PRODUCTS</span>

			<br><br>To complete our collection program in the country, the company Collect'us is provided by the international market.  We buy large amount of OEM virgin empty toner cartridges from our international partners. We can store large volumes in our warehouses.  At reception, all cartridges are controlled according to strict quality criteria. To pass it successfully and minimize damages during transit, we ask our partners to adhere to a packaging quality. 
			You can have more details on our terms and sending conditions.
			Contact us on our email address collectus@collectus.fr
			</div>
		</div>
	</div>
	<?php include('contact.php'); ?>
</div>
<div id="footer">
	<a href="" title="Accueil">Home</a> - <a href="" title="Mentions legales">Legal mentions</a>
</div>

<!-- Code javascript -->

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="../js/javascript.js"></script>
<script> 
<!--
$(document).ready(
function () { 
	$(".menu li.has-sub").each(
	function () {
		var $ul = $(this).find("ul"); 
		$(this).hover(
		function () {			
			var tempHeight = $ul.css("height", "auto").height();
			$ul
			.height(0)
			.stop()
			.animate({ height: tempHeight.toString() }, 350);
		}, 
		function () {
			$ul
			.stop()
			.animate({ height: "0" }, 350);
		});
	});
});
-->
</script>
</body>
</html>